$('.tabs li').on('click', function() {
    var $this = $(this)
    var index = $this.index()
    var panelWidth = $('.panel').width()
    console.log(panelWidth)
    console.log(index)
    $this.addClass('active').siblings().removeClass('active')
    $this.parents('.mod-tab').find('.panels_ct')
        .animate({ left: -panelWidth * index })
        //$('.panels_ct').animate({ left: -panelWidth * index })
})